services:
  pg:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: quadro
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./src/migrations:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
